version: '3.3'
name: servicechain-actions
services:
  CN-0:
    hostname: CN-0
    image: klaytn/klaytn:latest
    ports:
      - '32323'
      - '8551'
      - '61001'
    entrypoint:
      - /bin/bash
      - -c
      - |
        mkdir -p /klaytn
        echo '{"config":{"chainId":1000,"istanbulCompatibleBlock":0,"londonCompatibleBlock":0,"ethTxTypeCompatibleBlock":0,"istanbul":{"epoch":3600,"policy":0,"sub":22},"unitPrice":0,"deriveShaImpl":2,"governance":null},"timestamp":"0x6274b3e5","extraData":"0x0000000000000000000000000000000000000000000000000000000000000000f85ad59425c274e622c4deb1dcfa211e75b7b4671cdb0db2b8410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0","governanceData":null,"blockScore":"0x1","alloc":{"25c274e622c4deb1dcfa211e75b7b4671cdb0db2":{"balance":"0x446c3b15f9926687d2c40534fdb564000000000000"}},"number":"0x0","gasUsed":"0x0","parentHash":"0x0000000000000000000000000000000000000000000000000000000000000000"}' > /klaytn/genesis.json
        echo '["kni://aee3ab7a07053c0fe5af8033341250f74473dd280423c99e92c24a86b41332480e6d58ed9e731ee410046980b2218a789adc2adb00fa192d39cd79ffbe48e2b5@172.16.100.10:32323?discport=0\u0026ntype=cn"]' > /klaytn/static-nodes.json
        kcn --datadir "/klaytn" init "/klaytn/genesis.json"
        echo "# docker-compose" >> /klaytn-docker-pkg/conf/kcnd.conf
        echo 'NETWORK=""' >> /klaytn-docker-pkg/conf/kcnd.conf
        echo 'DATA_DIR="/klaytn"' >> /klaytn-docker-pkg/conf/kcnd.conf
        echo 'LOG_DIR="$$DATA_DIR/log"' >> /klaytn-docker-pkg/conf/kcnd.conf
        echo 'RPC_ENABLE=1' >> /klaytn-docker-pkg/conf/kcnd.conf
        echo 'RPC_API="db,klay,net,web3,miner,personal,txpool,debug,admin,istanbul,mainbridge,subbridge"' >> /klaytn-docker-pkg/conf/kcnd.conf
        echo 'NETWORK_ID="9999"' >> /klaytn-docker-pkg/conf/kcnd.conf
        echo 'NO_DISCOVER=1' >> /klaytn-docker-pkg/conf/kcnd.conf
        echo 'ADDITIONAL="$$ADDITIONAL --identity \"CN-0\""' >> /klaytn-docker-pkg/conf/kcnd.conf
        echo 'ADDITIONAL="$$ADDITIONAL --nodekeyhex 1dd4dc19688dde6b519f3d305349fa7cbc6f5c4195e72e0d12b665b2bc39a3a1"' >> /klaytn-docker-pkg/conf/kcnd.conf
        echo 'REWARDBASE=0x25c274E622C4deB1dCFA211E75b7b4671cDb0db2' >> /klaytn-docker-pkg/conf/kcnd.conf
        echo 'ADDITIONAL="$$ADDITIONAL --debug --metrics --prometheus"' >> /klaytn-docker-pkg/conf/kcnd.conf
        /klaytn-docker-pkg/bin/kcnd start
        tail -F klaytn/log/kcnd.out
    networks:
      app_net_actions:
        ipv4_address: 172.16.100.10
    restart: "no"
  PN-0:
    hostname: PN-0
    image: klaytn/klaytn:latest
    ports:
      - '32323'
      - '8551'
      - '61001'
    entrypoint:
      - /bin/bash
      - -c
      - |
        mkdir -p /klaytn
        echo '{"config":{"chainId":1000,"istanbulCompatibleBlock":0,"londonCompatibleBlock":0,"ethTxTypeCompatibleBlock":0,"istanbul":{"epoch":3600,"policy":0,"sub":22},"unitPrice":0,"deriveShaImpl":2,"governance":null},"timestamp":"0x6274b3e5","extraData":"0x0000000000000000000000000000000000000000000000000000000000000000f85ad59425c274e622c4deb1dcfa211e75b7b4671cdb0db2b8410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0","governanceData":null,"blockScore":"0x1","alloc":{"25c274e622c4deb1dcfa211e75b7b4671cdb0db2":{"balance":"0x446c3b15f9926687d2c40534fdb564000000000000"}},"number":"0x0","gasUsed":"0x0","parentHash":"0x0000000000000000000000000000000000000000000000000000000000000000"}' > /klaytn/genesis.json
        echo '["kni://aee3ab7a07053c0fe5af8033341250f74473dd280423c99e92c24a86b41332480e6d58ed9e731ee410046980b2218a789adc2adb00fa192d39cd79ffbe48e2b5@172.16.100.10:32323?discport=0\u0026ntype=cn"]' > /klaytn/static-nodes.json
        kpn --datadir "/klaytn" init "/klaytn/genesis.json"
        echo "# docker-compose" >> /klaytn-docker-pkg/conf/kpnd.conf
        echo 'NETWORK=""' >> /klaytn-docker-pkg/conf/kpnd.conf
        echo 'DATA_DIR="/klaytn"' >> /klaytn-docker-pkg/conf/kpnd.conf
        echo 'LOG_DIR="$$DATA_DIR/log"' >> /klaytn-docker-pkg/conf/kpnd.conf
        echo 'RPC_ENABLE=1' >> /klaytn-docker-pkg/conf/kpnd.conf
        echo 'RPC_API="db,klay,net,web3,miner,personal,txpool,debug,admin,istanbul,mainbridge,subbridge"' >> /klaytn-docker-pkg/conf/kpnd.conf
        echo 'NETWORK_ID="9999"' >> /klaytn-docker-pkg/conf/kpnd.conf
        echo 'NO_DISCOVER=1' >> /klaytn-docker-pkg/conf/kpnd.conf
        echo 'ADDITIONAL="$$ADDITIONAL --identity \"PN-0\""' >> /klaytn-docker-pkg/conf/kpnd.conf
        echo 'ADDITIONAL="$$ADDITIONAL --nodekeyhex 8f2f5b76d000ba88d297e4971ac1228f3bce9de5e7b3e075545e1ff2a00c5a84"' >> /klaytn-docker-pkg/conf/kpnd.conf
        echo 'ADDITIONAL="$$ADDITIONAL --txpool.nolocals"' >> /klaytn-docker-pkg/conf/kpnd.conf
        echo 'ADDITIONAL="$$ADDITIONAL --debug --metrics --prometheus"' >> /klaytn-docker-pkg/conf/kpnd.conf
        /klaytn-docker-pkg/bin/kpnd start
        sleep 1
        tail -F klaytn/log/kpnd.out
    networks:
      app_net_actions:
        ipv4_address: 172.16.100.11
    restart: "no"
  EN-0:
    hostname: EN-0
    image: klaytn/klaytn:latest
    ports:
      - '32323'
      - '8102:8551'
      - '61001'
      - '50505'
    entrypoint:
      - /bin/bash
      - -c
      - |
        mkdir -p /klaytn
        echo '{"config":{"chainId":1000,"istanbulCompatibleBlock":0,"londonCompatibleBlock":0,"ethTxTypeCompatibleBlock":0,"istanbul":{"epoch":3600,"policy":0,"sub":22},"unitPrice":0,"deriveShaImpl":2,"governance":null},"timestamp":"0x6274b3e5","extraData":"0x0000000000000000000000000000000000000000000000000000000000000000f85ad59425c274e622c4deb1dcfa211e75b7b4671cdb0db2b8410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0","governanceData":null,"blockScore":"0x1","alloc":{"25c274e622c4deb1dcfa211e75b7b4671cdb0db2":{"balance":"0x446c3b15f9926687d2c40534fdb564000000000000"}},"number":"0x0","gasUsed":"0x0","parentHash":"0x0000000000000000000000000000000000000000000000000000000000000000"}' > /klaytn/genesis.json
        echo '["kni://590c3e2a9eae98d798ecef2ba4cc17e3c200b3e450882bc5e4a7bff60cca0dad3dbb81a490c3c9f5fe30bfe921f509281ae2701e744917e195073e12789b5468@172.16.100.11:32323?discport=0\u0026ntype=pn"]' > /klaytn/static-nodes.json
        ken --datadir "/klaytn" init "/klaytn/genesis.json"
        echo "# docker-compose" >> /klaytn-docker-pkg/conf/kend.conf
        echo 'NETWORK=""' >> /klaytn-docker-pkg/conf/kend.conf
        echo 'DATA_DIR="/klaytn"' >> /klaytn-docker-pkg/conf/kend.conf
        echo 'LOG_DIR="$$DATA_DIR/log"' >> /klaytn-docker-pkg/conf/kend.conf
        echo 'RPC_ENABLE=1' >> /klaytn-docker-pkg/conf/kend.conf
        echo 'RPC_API="db,klay,net,web3,miner,personal,txpool,debug,admin,istanbul,mainbridge,subbridge"' >> /klaytn-docker-pkg/conf/kend.conf
        echo 'NETWORK_ID="9999"' >> /klaytn-docker-pkg/conf/kend.conf
        echo 'NO_DISCOVER=1' >> /klaytn-docker-pkg/conf/kend.conf
        echo 'ADDITIONAL="$$ADDITIONAL --identity \"EN-0\""' >> /klaytn-docker-pkg/conf/kend.conf
        echo 'ADDITIONAL="$$ADDITIONAL --nodekeyhex 1e2161f7c6b6e5293f8bddd26e939a280973b3b95af3aae7a524fe31f62bd56a"' >> /klaytn-docker-pkg/conf/kend.conf
        echo 'SC_MAIN_BRIDGE=1' >> /klaytn-docker-pkg/conf/kend.conf
        echo 'SC_MAIN_BRIDGE_PORT=50505' >> /klaytn-docker-pkg/conf/kend.conf
        echo 'SC_MAIN_BRIDGE_INDEXING=1' >> /klaytn-docker-pkg/conf/kend.conf
        echo 'ADDITIONAL="$$ADDITIONAL --debug --metrics --prometheus"' >> /klaytn-docker-pkg/conf/kend.conf
        /klaytn-docker-pkg/bin/kend start
        sleep 3
        parentAccount=`ken attach --exec "personal.importRawKey('1dd4dc19688dde6b519f3d305349fa7cbc6f5c4195e72e0d12b665b2bc39a3a1', '')" http://localhost:8551 | cut -d "\"" -f 2`
        echo "parentAccount is $$parentAccount" >> /klaytn/log/init.log
        ken attach --exec "personal.unlockAccount('$$parentAccount', '', 999999999)" http://localhost:8551 >> /klaytn/log/init.log
        tail -F klaytn/log/kend.out
    networks:
      app_net_actions:
        ipv4_address: 172.16.100.12
    restart: "no"
  SCN-0:
    hostname: SCN-0
    image: klaytn/klaytn:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '32323'
      - '8103:8551'
      - '61001'
      - '50506'
      - '7551'
    volumes:
      - ./certs:/klaytn/data/session
    entrypoint:
      - /bin/bash
      - -c
      - |
        mkdir -p /klaytn
        echo '{"config":{"chainId":1004,"istanbul":{"epoch":604800,"policy":0,"sub":21},"unitPrice":25000000000,"deriveShaImpl":0,"governance":{"governingNode":"0x7c24f4decc7a59f915d370faf89c63519e99bfcf","governanceMode":"none"}},"timestamp":"0x6274b3e6","extraData":"0x0000000000000000000000000000000000000000000000000000000000000000f85ad5947c24f4decc7a59f915d370faf89c63519e99bfcfb8410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0","governanceData":null,"blockScore":"0x1","alloc":{"7c24f4decc7a59f915d370faf89c63519e99bfcf":{"balance":"0x446c3b15f9926687d2c40534fdb564000000000000"}},"number":"0x0","gasUsed":"0x0","parentHash":"0x0000000000000000000000000000000000000000000000000000000000000000"}' > /klaytn/genesis.json
        echo '["kni://308478e65ffe43fca4a00bbf3d7bbce9ae46559458cedcbfe7d2f20138b46ad889870e0a883c600775fe95028b01715fab7912458b34205d7f4ec771beab7fb3@172.16.100.13:32323?discport=0"]' > /klaytn/static-nodes.json
        echo '["kni://880e032124a514fdf0604b4a51b53a7a6589f3e35438c141d496a7f794ef05faa12538d988c6df0d2207b6b0a55eef14b2ead6efe8c1c48e7b3289366b2e74db@172.16.100.12:50505?discport=0\u0026ntype=en"]' > /klaytn/main-bridges.json
        kscn --datadir "/klaytn" init "/klaytn/genesis.json"
        echo "# docker-compose" >> /klaytn-docker-pkg/conf/kscnd.conf
        echo 'NETWORK=""' >> /klaytn-docker-pkg/conf/kscnd.conf
        echo 'DATA_DIR="/klaytn"' >> /klaytn-docker-pkg/conf/kscnd.conf
        echo 'LOG_DIR="$$DATA_DIR/log"' >> /klaytn-docker-pkg/conf/kscnd.conf
        echo 'RPC_ENABLE=1' >> /klaytn-docker-pkg/conf/kscnd.conf
        echo 'RPC_API="db,klay,net,web3,miner,personal,txpool,debug,admin,istanbul,mainbridge,subbridge"' >> /klaytn-docker-pkg/conf/kscnd.conf
        echo 'NETWORK_ID="9999"' >> /klaytn-docker-pkg/conf/kscnd.conf
        echo 'NO_DISCOVER=1' >> /klaytn-docker-pkg/conf/kscnd.conf
        echo 'ADDITIONAL="$$ADDITIONAL --identity \"SCN-0\""' >> /klaytn-docker-pkg/conf/kscnd.conf
        echo 'ADDITIONAL="$$ADDITIONAL --nodekeyhex 6a98c76bae11151c5d74f9a007fdf689a7ca8aa3a78b1268fddf6d5df5348cf1"' >> /klaytn-docker-pkg/conf/kscnd.conf
        echo 'PORT=32323' >> /klaytn-docker-pkg/conf/kscnd.conf
        echo 'ADDITIONAL="$$ADDITIONAL --parentchainid 1000"' >> /klaytn-docker-pkg/conf/kscnd.conf
        echo 'SC_SUB_BRIDGE=1' >> /klaytn-docker-pkg/conf/kscnd.conf
        echo 'SC_SUB_BRIDGE_PORT=50506' >> /klaytn-docker-pkg/conf/kscnd.conf
        echo 'ADDITIONAL="$$ADDITIONAL --debug --metrics --prometheus"' >> /klaytn-docker-pkg/conf/kscnd.conf
        /klaytn-docker-pkg/bin/kscnd start
        sleep 30
        childAccount=`kscn attach --exec "personal.importRawKey('6a98c76bae11151c5d74f9a007fdf689a7ca8aa3a78b1268fddf6d5df5348cf1', '')" http://localhost:8551 | cut -d "\"" -f 2`
        echo "childAccount is $$childAccount" >> /klaytn/log/init.log
        kscn attach --exec "personal.unlockAccount('$$childAccount', '', 999999999)" http://localhost:8551 >> /klaytn/log/init.log
        kscn attach --exec "klay.sendTransaction({from:'$$childAccount', to:subbridge.childOperator, value: web3.toPeb(10000000000000000000000000000000, 'KLAY')})" http://localhost:8551 >> /klaytn/log/init.log
        tail -F klaytn/log/kscnd.out
    networks:
      app_net_actions:
        ipv4_address: 172.16.100.13
    restart: "no"
  prometheus:
    hostname: prometheus
    image: prom/prometheus:v2.3.2
    ports:
      - 9090
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      app_net_actions:
        ipv4_address: 172.16.100.9
    restart: "no"

networks:
  # In order to deploy multiple docker-compose files, replace the bridge name `app_net_my_driver_name` with another name, e.g., `app_net_my_driver_name_1`
  # Also, you have to use different subnet too, e.g., 172.16.238.0/24
  # You have to replace all occurance of the bridge name and subnet; in vim, below commands will help.
  # :%s/app_net_my_driver_name/app_net_my_driver_name_1/g
  # :%s/172.16.238/172.16.238/g
  app_net_actions:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.100.0/24
