name: "servicechain-actions-henry"
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
env:
  DOCKER_COMPOSE_ENV_FILE: .env_henry
jobs:
  remote-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout klaytn
      uses: actions/checkout@v3
      with:
        repository: henry-will/klaytn
        ref: dev
        path: test/klaytn/src
    - run: ls -al test/klaytn/src

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./test/klaytn
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/klaytn:latest

    - name: Start containers
      run: docker-compose -f "docker-compose-servicechain.yml" --env-file $DOCKER_COMPOSE_ENV_FILE up -d

    - name: Docker composer version
      run: docker-compose -f "docker-compose-servicechain.yml" --env-file $DOCKER_COMPOSE_ENV_FILE version

    - name: Check Status containers
      run: docker-compose -f "docker-compose-servicechain.yml" --env-file $DOCKER_COMPOSE_ENV_FILE ps

    - name: Send klay to parent and child operators, wait more then halve minute for loading SCN
      run: sleep 30        

    - name: Check Parent EN Files
      run: docker-compose -f "docker-compose-servicechain.yml" --env-file $DOCKER_COMPOSE_ENV_FILE exec -T EN-0 ls /klaytn/log

    - name: Check Child SCN Files
      run: docker-compose -f "docker-compose-servicechain.yml" --env-file $DOCKER_COMPOSE_ENV_FILE exec -T SCN-0 ls /klaytn/log

    - name: Check EN Operator
      run: docker-compose -f "docker-compose-servicechain.yml" --env-file $DOCKER_COMPOSE_ENV_FILE exec -T EN-0 cat /klaytn/log/init.log

    - name: Check SCN Operator
      run: docker-compose -f "docker-compose-servicechain.yml" --env-file $DOCKER_COMPOSE_ENV_FILE exec -T SCN-0 cat /klaytn/log/init.log

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 12
    - run: cd test && npm i
    - run: which bash
    - run: ls -al

    - name: Make bridge-info.json
      run: bash scripts/make-bridge-info.sh ./scripts/bridge-info-template.json ./test/common/bridge-info.json $DOCKER_COMPOSE_ENV_FILE

    - name: Test the erc20 value transfer
      run: cd test/erc20 && bash run_testcase.sh

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose-servicechain.yml" --env-file $DOCKER_COMPOSE_ENV_FILE down
