name: "servicechain-actions"
on:
   schedule:
     - cron: '0,10 * * * *'
   workflow_dispatch:
      inputs:
         logLevel:
            description: 'Log level'     
            required: true
            default: 'warning'
         tags:
            description: 'Test scenario tags'
jobs:
  docker-compose:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Start containers
      run: docker-compose -f "docker-compose-servicechain.yml" up -d

    - name: Do Some Test
      run: echo $GITHUB_SHA

    - name: Check Status contrainers
      run: docker-compose -f "docker-compose-servicechain.yml" ps

    - name: Check EN Status contrainers
      run: docker-compose -f "docker-compose-servicechain.yml" exec --tty EN-0 cat /klaytn/log/init.log

    - name: Check SCN Status contrainers
      run: docker-compose -f "docker-compose-servicechain.yml" exec --tty SCN-0 cat /klaytn/log/init.log

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose-servicechain.yml" down
