name: "slack-noti"
on:
  workflow_dispatch:
    inputs:
      envFile:
        description: 'Env file name'
        required: true
        default: '.env_new_new'

env:
  DOCKER_COMPOSE_ENV_FILE: ${{ inputs.envFile }}
jobs:
  docker-compose:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TEST }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: remote-tests-bot
          status: SUCCESS ${{ DOCKER_COMPOSE_ENV_FILE }}
          color: good
      
      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TEST }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: remote-tests-bot
          status: FAILED
          color: danger
